NAME_DICTIONARY = {'gan dalf': 'gandalf',
                   'gandalf voiceover': 'gandalf',
                   'galadriel voice over': 'galadriel',
                   'galadriel voiceover': 'galadriel',
                   'galadriel voice-over': 'galadriel',
                   'BILBO voiceover': 'BILBO',
                   'SAM voiceover': 'SAM',
                   'saruman voice over ': 'saruman',
                   'elrond voiceover': 'elrond',
                   'frodo voice over': 'frodo',
                   'frodo voice': 'frodo',
                   'frodo ': 'frodo',
                   '\xa0gandalf': 'gandalf',
                   'male': 'Male',
                   'Males': 'Male',
                   'frodo baggins': 'frodo',
                   'bilbo baggins': 'bilbo',
                   'aragorn ii elessar': 'aragorn',
                   'samwise gamgee': 'sam',
                   'peregrin took': 'pippin',
                   'théoden': 'theoden',
                   'owyn': 'eowyn',
                   'smeagol': 'gollum',
                   '(gollum': 'gollum',
                   'mouth of sauron': 'sauron',
                   'sam voiceover': 'sam',
                   'arwen voiceover': 'arwen',
                   'gandalf voice over': 'gandalf',
                   'saruman voice over': 'saruman',
                   'sauron voice': 'sauron',
                   'bilbo voiceover': 'bilbo'
                   }
RACE_DICTIONARY = {
                    'Hobbit': 'Hobbits'
                }
