NAME_DICTIONARY = {'gan dalf': 'gandalf',
                   'gandalf voiceover': 'gandalf',
                   'galadriel voice over': 'galadriel',
                   'galadriel voiceover': 'galadriel',
                   'galadriel voice-over': 'galadriel',
                   'BILBO voiceover': 'BILBO',
                   'SAM voiceover': 'SAM',
                   'saruman voice over ': 'saruman',
                   'elrond voiceover': 'elrond',
                   'frodo voice over': 'frodo',
                   'frodo voice': 'frodo',
                   'frodo ': 'frodo',
                   '\xa0gandalf': 'gandalf',
                   'male': 'Male',
                   'Males': 'Male'
                   }